# Generated by Django 3.2.2 on 2023-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20230512_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Аванс', 'Аванс'), ('Оплачено', 'Оплачено')], default='Ожидание', max_length=120),
        ),
    ]
